"""Add club and membership models

Revision ID: 334d37b68fc1
Revises: be22609b3228
Create Date: 2024-12-02 17:55:33.440228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334d37b68fc1'
down_revision = 'be22609b3228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('president_id', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['president_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('memberships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'club_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memberships')
    op.drop_table('clubs')
    # ### end Alembic commands ###
