"""empty message

Revision ID: 57018b88f96e
Revises: 61bf5bfa3e40
Create Date: 2024-12-25 15:27:11.985551

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57018b88f96e"
down_revision = "61bf5bfa3e40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint("fk_events_category_id", type_="foreignkey")
        batch_op.create_foreign_key("fk_events_category_id", "categories", ["category_id"], ["id"], ondelete="SET NULL")
        batch_op.create_foreign_key("fk_events_club_id", "clubs", ["club_id"], ["id"], ondelete="CASCADE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint("fk_events_category_id", type_="foreignkey")
        batch_op.drop_constraint("fk_events_club_id", type_="foreignkey")
        batch_op.create_foreign_key("fk_events_category_id", "categories", ["category_id"], ["id"])
        batch_op.create_foreign_key("fk_events_club_id", "clubs", ["club_id"], ["id"])

    # ### end Alembic commands ###
