"""empty message

Revision ID: 5fb1a2a9a098
Revises: dc542b09cf35
Create Date: 2024-12-23 14:06:30.486714

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5fb1a2a9a098"
down_revision = "dc542b09cf35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_events_category_id", "categories", ["category_id"], ["id"])  # Add a name for the foreign key constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint("fk_events_category_id", type_="foreignkey")  # Use the same name here
        batch_op.drop_column("category_id")

    # ### end Alembic commands ###
