"""empty message

Revision ID: 61bf5bfa3e40
Revises: feb3858c96fa
Create Date: 2024-12-24 18:50:48.302122

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = "61bf5bfa3e40"
down_revision = "feb3858c96fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    constraints = inspector.get_foreign_keys("event_feedbacks")
    constraint_names = [constraint["name"] for constraint in constraints]

    with op.batch_alter_table("event_feedbacks", schema=None) as batch_op:
        if "fk_event_feedbacks_event_id" in constraint_names:
            batch_op.drop_constraint("fk_event_feedbacks_event_id", type_="foreignkey")
        batch_op.create_foreign_key("fk_event_feedbacks_event_id", "events", ["event_id"], ["id"], ondelete="CASCADE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_feedbacks", schema=None) as batch_op:
        batch_op.drop_constraint("fk_event_feedbacks_event_id", type_="foreignkey")
        batch_op.create_foreign_key("fk_event_feedbacks_event_id", "events", ["event_id"], ["id"])

    # ### end Alembic commands ###
