"""empty message

Revision ID: 92fa37666213
Revises: 8c4b11be3ea8
Create Date: 2024-12-04 14:46:49.811382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fa37666213'
down_revision = '8c4b11be3ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_posts_author_id', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_author_id', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
