"""empty message

Revision ID: f4acaa377d5d
Revises: d12790671405
Create Date: 2024-12-05 00:38:09.578840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4acaa377d5d'
down_revision = 'd12790671405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_username', ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_email')

    # ### end Alembic commands ###
